/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as PreviewDraftRouteImport } from './routes/preview.draft'
import { Route as RPublicIdRouteImport } from './routes/r.$publicId'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as SurveysIndexRouteImport } from './routes/surveys.index'
import { Route as SurveysIdRouteImport } from './routes/surveys.$id'
import { Route as RPublicIdPreviewRouteImport } from './routes/r.$publicId.preview'
import { Route as RPublicIdTestRouteImport } from './routes/r.$publicId.test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
})
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
})
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
})
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
})
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
})
const PreviewDraftRoute = PreviewDraftRouteImport.update({
  id: '/preview/draft',
  path: '/preview/draft',
  getParentRoute: () => rootRouteImport,
})
const RPublicIdRoute = RPublicIdRouteImport.update({
  id: '/r/$publicId',
  path: '/r/$publicId',
  getParentRoute: () => rootRouteImport,
})
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
})
const SurveysIndexRoute = SurveysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SurveysRoute,
})
const SurveysIdRoute = SurveysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SurveysRoute,
})
const RPublicIdPreviewRoute = RPublicIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => RPublicIdRoute,
})
const RPublicIdTestRoute = RPublicIdTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => RPublicIdRoute,
})

const SurveysRouteChildren = {
  SurveysIdRoute: SurveysIdRoute,
  SurveysIndexRoute: SurveysIndexRoute,
}

const SurveysRouteWithChildren =
  SurveysRoute._addFileChildren(SurveysRouteChildren)

const RPublicIdRouteChildren = {
  RPublicIdPreviewRoute: RPublicIdPreviewRoute,
  RPublicIdTestRoute: RPublicIdTestRoute,
}

const RPublicIdRouteWithChildren = RPublicIdRoute._addFileChildren(
  RPublicIdRouteChildren,
)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SurveysRoute: SurveysRouteWithChildren,
  PreviewDraftRoute: PreviewDraftRoute,
  RPublicIdRoute: RPublicIdRouteWithChildren,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
