/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppWorkspaceSlugRouteImport } from './routes/app/$workspaceSlug'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppWorkspaceSlugSurveysRouteImport } from './routes/app/$workspaceSlug/surveys'
import { Route as AppWorkspaceSlugDashboardRouteImport } from './routes/app/$workspaceSlug/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceSlugRoute = AppWorkspaceSlugRouteImport.update({
  id: '/app/$workspaceSlug',
  path: '/app/$workspaceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceSlugSurveysRoute = AppWorkspaceSlugSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppWorkspaceSlugDashboardRoute =
  AppWorkspaceSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/app/$workspaceSlug': typeof AppWorkspaceSlugRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/$workspaceSlug/dashboard': typeof AppWorkspaceSlugDashboardRoute
  '/app/$workspaceSlug/surveys': typeof AppWorkspaceSlugSurveysRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/app/$workspaceSlug': typeof AppWorkspaceSlugRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/$workspaceSlug/dashboard': typeof AppWorkspaceSlugDashboardRoute
  '/app/$workspaceSlug/surveys': typeof AppWorkspaceSlugSurveysRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/app/$workspaceSlug': typeof AppWorkspaceSlugRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/$workspaceSlug/dashboard': typeof AppWorkspaceSlugDashboardRoute
  '/app/$workspaceSlug/surveys': typeof AppWorkspaceSlugSurveysRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/app/$workspaceSlug'
    | '/auth/login'
    | '/auth/register'
    | '/app/$workspaceSlug/dashboard'
    | '/app/$workspaceSlug/surveys'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/app/$workspaceSlug'
    | '/auth/login'
    | '/auth/register'
    | '/app/$workspaceSlug/dashboard'
    | '/app/$workspaceSlug/surveys'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/app/$workspaceSlug'
    | '/auth/login'
    | '/auth/register'
    | '/app/$workspaceSlug/dashboard'
    | '/app/$workspaceSlug/surveys'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AppWorkspaceSlugRoute: typeof AppWorkspaceSlugRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$workspaceSlug': {
      id: '/app/$workspaceSlug'
      path: '/app/$workspaceSlug'
      fullPath: '/app/$workspaceSlug'
      preLoaderRoute: typeof AppWorkspaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$workspaceSlug/surveys': {
      id: '/app/$workspaceSlug/surveys'
      path: '/surveys'
      fullPath: '/app/$workspaceSlug/surveys'
      preLoaderRoute: typeof AppWorkspaceSlugSurveysRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/app/$workspaceSlug/dashboard': {
      id: '/app/$workspaceSlug/dashboard'
      path: '/dashboard'
      fullPath: '/app/$workspaceSlug/dashboard'
      preLoaderRoute: typeof AppWorkspaceSlugDashboardRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
  }
}

interface AppWorkspaceSlugRouteChildren {
  AppWorkspaceSlugDashboardRoute: typeof AppWorkspaceSlugDashboardRoute
  AppWorkspaceSlugSurveysRoute: typeof AppWorkspaceSlugSurveysRoute
}

const AppWorkspaceSlugRouteChildren: AppWorkspaceSlugRouteChildren = {
  AppWorkspaceSlugDashboardRoute: AppWorkspaceSlugDashboardRoute,
  AppWorkspaceSlugSurveysRoute: AppWorkspaceSlugSurveysRoute,
}

const AppWorkspaceSlugRouteWithChildren =
  AppWorkspaceSlugRoute._addFileChildren(AppWorkspaceSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  AppWorkspaceSlugRoute: AppWorkspaceSlugRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
